categories:
  - title: 💥 Breaking changes
    labels:
      - breaking
  - title: '🚀 New features and improvements'
    labels:
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: 📝 Documentation updates
    labels:
      - documentation
  - title: '🧰 Maintenance'
    labels:
      - chore
      - maintenance
  - title: 📦 Dependency updates
    labels:
      - dependencies
    collapse-after: 15

exclude-labels:
  - skip-changelog
  - invalid

template: |
  ## Changes

  $CHANGES

  ## Contributors

  Thanks to $CONTRIBUTORS for your contributions to this release!

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
no-changes-template: '- No changes'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch

autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'