_extends: containers:.github/release-drafter/base.yaml
name-template: "excalidraw-v$RESOLVED_VERSION"
tag-template: "excalidraw-v$RESOLVED_VERSION"
tag-prefix: excalidraw-v
include-paths:
  - "excalidraw/"
