version: "3"

tasks:
  init:
    desc: Initialize Homebrew dependencies.
    cmds:
      - brew install {{.PACKAGES}} {{.CLI_ARGS}}
    preconditions:
      - sh: command -v brew
        msg: |
          Homebrew has not been installed on the device.
    vars:
      PACKAGES: >-
        direnv
        gitleaks
        ipcalc
        markdownlint-cli
        pre-commit
        prettier
        yamllint
        gettext
        mkdocs
        go-task
        jq
        yq
    silent: true
