# https://docs.docker.com/build/ci/github-actions/multi-platform/
name: Create and publish a Docker image to GitHub Container Registry
 
on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  OWNER_NAME: ${{ GITHUB_REPOSITORY_OWNER }}
  APP_NAME: utils
 
jobs:
  build-platform-images:
    name: Build multi-platform image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ GITHUB_ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) from Container
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ env.APP_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.APP_NAME }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.OWNER_NAME }}/${{ env.APP_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
