name: Build and publish Image
 
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
      registry:
        required: false
        type: string
      owner:
        required: false
        type: string
      platforms:
        required: false
        type: string
  workflow_dispatch:
    inputs:
      app:
        required: true
        type: string
        description: 'Application to build (i.e: toolbox)'
      registry:
        required: false
        type: string
        description: 'Registry to be used (default: ghcr.io)'
      owner:
        required: false
        type: string
        description: 'Owner to be used (default: repo owner)'
      platforms:
        required: false
        type: string
        description: 'Platforms to be used to build (default: linux/amd64,linux/arm64)'

env:
  app: ${{ inputs.app }}
  registry: ${{ inputs.registry == null && 'ghcr.io' || inputs.registry }}
  owner: ${{ inputs.owner == null && github.repository_owner || inputs.owner }}
  platforms: ${{ inputs.platforms == null && 'linux/amd64,linux/arm64' || inputs.platforms }}
 
jobs:
  # https://docs.docker.com/build/ci/github-actions/multi-platform/
  build-platform-images:
    name: Build multi-platform image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # https://brandur.org/fragments/github-actions-env-vars-in-env-vars
      - name: "Set environmental variables"
        run: |
          echo "image=${{ env.registry }}/${{ env.owner }}/${{ env.app }}" >> $GITHUB_ENV
      # Debug environment variables
      - run: echo "${{ env.app }};${{ env.version }};${{ env.registry }};${{ env.owner }};${{ env.platforms }};${{ env.image }}"
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) from repository
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.image }}
          tags: |
            type=semver,pattern={{version}}
      
      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ env.app }}
          platforms: ${{ env.platforms }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          # https://github.com/docker/metadata-action
          tags: ${{ steps.meta.outputs.tags }}
      