name: Build and publish Images
 
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - '*/**'
      - '!*/*.md'
      - '!.github/**'
      - '!*'

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed folders
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 1
          matrix: true
          files_ignore: |
            */*.md
            .github/**
            *

      - run: echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"

  build-changed-images:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        paths: ${{ fromJSON(needs.find-changes.outputs.paths) }}
      max-parallel: 4
      fail-fast: false
    needs:
      - find-changes
    steps:
      # You can't call a local action on a repository without using the actions/checkout 
      - uses: actions/checkout@v4
      - uses: .github/workflows/build-push-image.yaml
        with:
          registry: ghcr.io
          owner: ${{ github.repository_owner }}
          platforms: linux/amd64,linux/arm64
          app: ${{ matrix.paths }}
          version: 1.0.0