name: Test Workflow
 
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - '*/**'
      - '!*/*.md'
      - '!.github/**'
      - '!*'

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      dirs: ${{ steps.changed-files.dirs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 2
          json: true
          quotepath: false

  do-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.find-out-changes.outputs.dirs)}}
    needs:
      - find-out-changes
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ matrix.dir }}""

