name: Test Workflow
 
on:
  workflow_dispatch:
  push:
    branches: ['main']
    # paths:
    #   - '*/**'
    #   - '!*/*.md'
    #   - '!.github/**'
    #   - '!*'

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 1
          matrix: true

      - run: echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"

  do-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        paths: ${{ fromJSON(needs.find-changes.outputs.paths) }}
      max-parallel: 4
      fail-fast: false
    needs:
      - find-changes
    steps:
      - uses: actions/checkout@v4
      - run: echo "${{ matrix.paths }}"

