name: Test Workflow
 
on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths:
      - '*/**'
      - '!*/*.md'
      - '!.github/**'
      - '!*'

jobs:
  find-changes:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          dir_names: true
          dir_names_max_depth: 1
          matrix: true
          files_ignore: |
            */*.md
            .github/**
            *

      - run: echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"

  do-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        paths: ${{ fromJSON(needs.find-changes.outputs.paths) }}
      max-parallel: 4
      fail-fast: false
    needs:
      - find-changes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) from Container
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ matrix.paths }}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: ${{ matrix.paths }}
          platforms: ${{ env.PLATFORMS }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ matrix.paths }}:latest,${{ env.REGISTRY }}/${{ env.OWNER_NAME }}/${{ matrix.paths }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

